
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")

    _global = []
    mf_struct = {}

    for row in cur:
        key = row['cust']
        if key not in mf_struct:
            mf_struct[key] = {'cust': row['cust'], '1_sum_quant': 0, '2_sum_quant': 0}
        entry = mf_struct[key]

    cur.execute("SELECT * FROM sales")
    for row in cur:
        for entry in mf_struct.values():
            if row['cust'] == entry['cust']:
                entry['1_sum_quant'] += row['quant']

    cur.execute("SELECT * FROM sales")
    for row in cur:
        for entry in mf_struct.values():
            if row['cust'] != entry['cust']:
                entry['2_sum_quant'] += row['quant']

    for entry in sorted(mf_struct.values(), key=lambda e: e['cust']):
        if entry['1_sum_quant'] > 1000000:
            _global.append({'cust': entry['cust'], '1_sum_quant': entry['1_sum_quant'], '2_sum_quant': entry['2_sum_quant']})

    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())

if "__main__" == __name__:
    main()
    